apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ubuntu-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ubuntu-test
    spec:
      containers:
      - image: docker.io/ubuntu
        imagePullPolicy: Always
        name: ubuntu-test
        command:
          - /bin/sleep
          - infinity
