apiVersion: v1
kind: Service
metadata:
  name: tolerable-webhook
spec:
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
