log_level = "INFO"
ssl_key_path = "/opt/tolerable/ssl/tls.key"
ssl_cert_path = "/opt/tolerable/ssl/tls.crt"
supported_architectures = [ "amd64", "arm64" ]
[tolerations]
effect = "NoSchedule"
operator = "Equal"
key = "kubernetes.io/arch"
value= "arm64"
