on:
  push:
    tags:
      - '*'
name: Create Images
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      - uses: docker/setup-qemu-action@v2.1.0
        name: Setup QEMU
      - uses: docker/setup-buildx-action@v2.5.0
        name: Setup docker buildx
      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            petergrace/tolerable
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
