env:
  RUST_LOG: debug
on:
  push: {}
  pull_request:
    branches: [ "main" ]
name: CI
jobs:
  test:
    name: tolerable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'docker.io.toml'
          fileDir: './creds/'
          encodedString: ${{ secrets.DOCKER_IO_CREDS }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
