on: [push]
name: CI
jobs:
  test:
    name: tolerable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: table
      - uses: actions-rs/cargo@v1
        with:
          command: test
